Sia integrations Sia integrations `rclone` s3 setup guide
SiaFoundation/docs pull request #25
Opened 2023-12-03 03:39 UTC by skunk-ink

A `rclone` setup guide for Windows, Mac OS, and Linux, complete with setup screenshots for each system.

2023-12-04 15:21 UTC, n8maninger approved these changes

2023-12-05 00:11 UTC, skunk-ink commented on sia-integrations/s3-integrations/rclone.md
> +<figure><img src="../../.gitbook/assets/rclone-s3-integration/rclone-new-config-win-01.png" alt="" width="375"><figcaption></figcaption></figure>
Done.

2023-12-05 00:14 UTC, n8maninger requested changes

2023-12-05 00:24 UTC, skunk-ink commented on sia-integrations/s3-integrations/rclone.md
> +Make sure to replace `your_renterd_access_key` and `your_renterd_secret_key` with unique passphrases. They can be anything you want but must be at least 16 characters in length, and your secret key s
Done.

2023-12-05 00:25 UTC, n8maninger approved these changes

2023-12-05 00:26 UTC, merged