`rclone` guide updates
SiaFoundation/docs pull request #72
Opened 2024-04-22 08:10 UTC by skunk-ink

- Added `--s3-chunk-size 128MiB` and `--fast-list` flags to `rclone mount` commands
- Fixed `port` typo
- Removed out dated instructions for enabling S3

2024-04-22 09:56 UTC, ChrisSchinnerl requested changes

2024-04-22 09:56 UTC, ChrisSchinnerl commented on sia-integrations/s3-integrations/rclone.md
> +rclone mount renterd:/default ~/renterd_files/ --s3-chunk-size 128MiB --fast-list --vfs-cache-mode full --daemon
```suggestion
rclone mount renterd:/default ~/renterd_files/ --s3-chunk-size 120MiB --fast-list --vfs-cache-mode full --daemon
```

2024-04-22 09:56 UTC, ChrisSchinnerl commented on sia-integrations/s3-integrations/rclone.md
> +rclone mount renterd:/default X: --s3-chunk-size 128MiB --fast-list --vfs-cache-mode full
```suggestion
rclone mount renterd:/default X: --s3-chunk-size 120MiB --fast-list --vfs-cache-mode full
```

2024-04-22 09:56 UTC, ChrisSchinnerl commented on sia-integrations/s3-integrations/rclone.md
> +rclone mount renterd:/default ~/renterd_files/ --s3-chunk-size 128MiB --fast-list --vfs-cache-mode full --daemon
```suggestion
rclone mount renterd:/default ~/renterd_files/ --s3-chunk-size 120MiB --fast-list --vfs-cache-mode full --daemon
```

2024-04-22 23:21 UTC, n8maninger approved these changes

2024-04-23 08:10 UTC, ChrisSchinnerl approved these changes

2024-04-23 08:11 UTC, merged